### ISSUE TITLE
Client DPI - UDMSE

### ISSUE THREAD

**Issue by Antares84** [unpoller/dashboards#46]
Client DPI not working at all for UDM SE
Version: 4.2.12
Network Version: 9.1.120

**Comment by charlestephen** [comment]
Been having the same issue and am using a Cloud Gateway Ultra. 
Version 4.4.0
Network Version 9.4.11
The client DPI in is in UniFi but doesn't seem to be in the API somehow.

**Comment by disconn3ct** [comment]
Same here. UCG ultra. It worked on the linuxserver container but isn't working on the gateway.
```log
unifipoller-unifi-poller 2025/08/20 11:25:28 [INFO] UniFi Measurements Exported. Site: 1, Client: 80, UAP: 3, USG/UDM: 1, USW: 2, DPI Site/Client: 1/0, Desc: 200, Metric: 2450, Err: 0, 0s: 570, Req/Total: 226ms / 241.1ms
```
```yaml
image:
  repository: ghcr.io/unpoller/unpoller
  tag: v2.15.3
env:
  UP_UNIFI_DEFAULT_URL: "https://1.1.1.1"
  UP_UNIFI_DEFAULT_USER: unifipoller
  UP_INFLUXDB_DISABLE: "true"
  UP_UNIFI_DEFAULT_SAVE_DPI: "true"
  UP_UNIFI_DEFAULT_PASS:
    valueFrom:
      secretKeyRef:
        name: unifi-poller-account
        key: password
  UP_LOKI_DISABLE: "true"
```

<img width="2274" height="102" alt="Image" src="https://github.com/user-attachments/assets/d61a8600-f0f8-40f2-b206-c9ef08861f5f" />
